@startuml

left to right direction

class Tablero{
    - filas: int
    - columnas: int
    + colocarFicha(ficha: Ficha, fila: int, columna: int): void
    + moverFicha(ficha: Ficha, nuevaFila: int, nuevaColumna: int): void
}

abstract Ficha{
    - puntosSalud: int
    - danio: int
    - defensa: int
    - rango: int
    + desmayar(): void
    + atacar(): void
}

class Arquero{
    +ataqueEspecial(): void
}

class Mago{
    +ataqueEspecial(): void
}

class Tanque{
    +ataqueEspecial(): void
}

class Espadachin{
    +ataqueEspecial(): void
}

class TurnoJugador{
    - tablero: Tablero
    + prepararTurno(): void
    + seleccionarAtaque(ficha: Ficha, tipo: String): void
    + avanzarFaseCombate(): void
}

class TurnoEnemigo{
    - tablero: Tablero
    + ejecutarAtaques(): void
}


class Estadisticas{


}

interface ISistemaPuntuacion{
    + iniciarJuego(): void
    + cargarMapa(): void
    + cambiarPosicionFichas(): void
    + mostrarMenuEstadisticas(): void
}

'Notas
note "Se tienen que tener dos tableros, un jugador y un enemigo" as N1
note "Cada tablero esta confirmado por 4 filas y 3 columnas" as N2
note "Deben ser matrices poco pobladas" as N3
note "Cuando una unidad se desmaya la casilla queda bloqueada" as N4

'Relaciones de notas
Tablero -- N1
Tablero -- N2
Tablero -- N3
Tablero -- N4

'Relaciones
Ficha <|-- Arquero
Ficha <|-- Mago
Ficha <|-- Tanque
Ficha <|-- Espadachin


@enduml