@startuml

left to right direction

class Tablero{
    - filas: int
    - columnas: int
    + colocarFicha(ficha: Ficha, fila: int, columna: int): void
    + moverFicha(ficha: Ficha, nuevaFila: int, nuevaColumna: int): void
}

abstract class Ficha {
    - nombreFicha: String
    - puntosSalud: int
    - danio: int
    - defensa: int
    - rango: int
    - atacar: bool
    - desmayar: bool
    + getNombreFicha(): String
    + getPuntosSalud(): int
    + getDefensa(): int
    + getRango(): int
    + getAtacar(): bool
    + getDesmayar(): bool
    + setPuntosSalud(int puntos): void
    + setDanio(int danio): void
    + setDefensa(int defensa): void
    + setRango(int rango): void
    + setAtacar(bool atacar): void
}

class NodoFicha{
    - ficha: Ficha*
    - left: NodoFicha*
    - up: NodoFicha*
    - fila: int
    - columna: int
    + NodoFicha(ficha: Ficha*, posicionFila: int, posicionColumna: int)
    + ~NodoFicha()
    + getFicha(): Ficha*
    + getFila(): int
    + getColumna(): int
    + getLeft(): NodoFicha*
    + setLeft(NodoFicha* nodo): void
    + getUp(): NodoFicha*
    + setUp(NodoFicha* nodo): void
}

class MatrizPocoPoblada{
    - a_Fil: NodoFicha*
    - a_Col: NodoFicha*
    - fila: int
    - columna: int
    + mpp(nFill: int, nCol: int)
    + ~mpp()
    + buscarFicha(ficha: Ficha*, fila: int, columna:int): boolean
    + eliminarFicha(): boolean
    + agregarFicha(): boolean
}

class TurnoJugador{
    - tablero: Tablero
    + prepararTurno(): void
    + seleccionarAtaque(ficha: Ficha, tipo: String): void
    + avanzarFaseCombate(): void
}

class TurnoEnemigo{
    - tablero: Tablero
    + ejecutarAtaques(): void
}

class Estadisticas {

}

class SistemaJuego {

}

interface ISistemaJuego{
    + iniciarJuego(): void
    + cargarMapa(): void
    + cambiarPosicionFichas(): void
    + mostrarMenuEstadisticas(): void
}

' Notas
note "Se tienen que tener dos tableros, un jugador y un enemigo" as N1
note "Cada tablero esta confirmado por 4 filas y 3 columnas" as N2
note "Deben ser matrices poco pobladas" as N3
note "Cuando una unidad se desmaya la casilla queda bloqueada" as N4

' Relaciones de notas
Tablero -- N1
Tablero -- N2
Tablero -- N3
Tablero -- N4


NodoFicha --> Ficha : contiene
MatrizPocoPoblada --> NodoFicha : maneja

@enduml
